import type { BrandId } from "./types";

/** One downloadable woff2 file (latin subset). */
export interface FontFile {
  readonly weight: number;
  /** Public path under /fonts. */
  readonly file: string;
  readonly bytes: number;
}

export interface FontManifestEntry {
  readonly family: string;
  readonly slug: string;
  readonly role: string;
  readonly weights: readonly number[];
  readonly files: readonly FontFile[];
  readonly license: string;
  /** Public path of the license text shipped beside the font files. */
  readonly licenseFile: string;
  readonly licenseBytes: number;
  readonly googleUrl: string;
  /** Where the woff2 files were taken from. */
  readonly source: string;
  readonly brands: readonly BrandId[];
  readonly note: string;
}

/** Generated by the assets agent from the @fontsource packages. Latin subset only. */
export const FONTS_MANIFEST: readonly FontManifestEntry[] = [
  {
    "family": "Josefin Sans",
    "slug": "josefin-sans",
    "role": "Headings and titles (weight 300, caps via CSS with +0.04em tracking)",
    "weights": [
      300,
      400
    ],
    "files": [
      {
        "weight": 300,
        "file": "/fonts/josefin-sans/josefin-sans-latin-300-normal.woff2",
        "bytes": 12208
      },
      {
        "weight": 400,
        "file": "/fonts/josefin-sans/josefin-sans-latin-400-normal.woff2",
        "bytes": 12372
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/josefin-sans/OFL.txt",
    "licenseBytes": 4624,
    "googleUrl": "https://fonts.google.com/specimen/Josefin+Sans",
    "source": "@fontsource/josefin-sans@5.3.0, latin subset",
    "brands": [
      "ventures",
      "media",
      "academy",
      "club",
      "labs",
      "mazal"
    ],
    "note": "GN Labs uses it only for splash and labels; Mazal uses it on the web channel only."
  },
  {
    "family": "Manrope",
    "slug": "manrope",
    "role": "Body text; 300 for large headings in GN Commune; 600 for GN Labs h1",
    "weights": [
      300,
      400,
      500,
      600,
      700
    ],
    "files": [
      {
        "weight": 300,
        "file": "/fonts/manrope/manrope-latin-300-normal.woff2",
        "bytes": 14160
      },
      {
        "weight": 400,
        "file": "/fonts/manrope/manrope-latin-400-normal.woff2",
        "bytes": 14108
      },
      {
        "weight": 500,
        "file": "/fonts/manrope/manrope-latin-500-normal.woff2",
        "bytes": 14044
      },
      {
        "weight": 600,
        "file": "/fonts/manrope/manrope-latin-600-normal.woff2",
        "bytes": 14172
      },
      {
        "weight": 700,
        "file": "/fonts/manrope/manrope-latin-700-normal.woff2",
        "bytes": 14212
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/manrope/OFL.txt",
    "licenseBytes": 4383,
    "googleUrl": "https://fonts.google.com/specimen/Manrope",
    "source": "@fontsource/manrope@5.3.0, latin subset",
    "brands": [
      "ventures",
      "media",
      "academy",
      "club",
      "labs",
      "mazal",
      "commune"
    ],
    "note": ""
  },
  {
    "family": "Poppins",
    "slug": "poppins",
    "role": "UI: buttons, navigation, labels, badges",
    "weights": [
      400,
      500,
      600
    ],
    "files": [
      {
        "weight": 400,
        "file": "/fonts/poppins/poppins-latin-400-normal.woff2",
        "bytes": 7884
      },
      {
        "weight": 500,
        "file": "/fonts/poppins/poppins-latin-500-normal.woff2",
        "bytes": 7748
      },
      {
        "weight": 600,
        "file": "/fonts/poppins/poppins-latin-600-normal.woff2",
        "bytes": 8000
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/poppins/OFL.txt",
    "licenseBytes": 6175,
    "googleUrl": "https://fonts.google.com/specimen/Poppins",
    "source": "@fontsource/poppins@5.3.0, latin subset",
    "brands": [
      "ventures",
      "media",
      "academy",
      "club",
      "labs",
      "mazal"
    ],
    "note": ""
  },
  {
    "family": "Geist Mono",
    "slug": "geist-mono",
    "role": "Numerals and data (GN Academy; proposed for the umbrella)",
    "weights": [
      400,
      500
    ],
    "files": [
      {
        "weight": 400,
        "file": "/fonts/geist-mono/geist-mono-latin-400-normal.woff2",
        "bytes": 9864
      },
      {
        "weight": 500,
        "file": "/fonts/geist-mono/geist-mono-latin-500-normal.woff2",
        "bytes": 10116
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/geist-mono/OFL.txt",
    "licenseBytes": 4498,
    "googleUrl": "https://fonts.google.com/specimen/Geist+Mono",
    "source": "@fontsource/geist-mono@5.3.0, latin subset",
    "brands": [
      "ventures",
      "academy"
    ],
    "note": ""
  },
  {
    "family": "Archivo",
    "slug": "archivo",
    "role": "Mazal social creative: 800 pills and CTAs, 700 body",
    "weights": [
      700,
      800,
      900
    ],
    "files": [
      {
        "weight": 700,
        "file": "/fonts/archivo/archivo-latin-700-normal.woff2",
        "bytes": 14508
      },
      {
        "weight": 800,
        "file": "/fonts/archivo/archivo-latin-800-normal.woff2",
        "bytes": 14416
      },
      {
        "weight": 900,
        "file": "/fonts/archivo/archivo-latin-900-normal.woff2",
        "bytes": 13548
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/archivo/OFL.txt",
    "licenseBytes": 4503,
    "googleUrl": "https://fonts.google.com/specimen/Archivo",
    "source": "@fontsource/archivo@5.3.0, latin subset",
    "brands": [
      "mazal"
    ],
    "note": "Social kit channel only."
  },
  {
    "family": "Archivo Black",
    "slug": "archivo-black",
    "role": "Mazal social creative: headlines and stats (the kit's \"900 Archivo Black\")",
    "weights": [
      400
    ],
    "files": [
      {
        "weight": 400,
        "file": "/fonts/archivo-black/archivo-black-latin-400-normal.woff2",
        "bytes": 18604
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/archivo-black/OFL.txt",
    "licenseBytes": 4398,
    "googleUrl": "https://fonts.google.com/specimen/Archivo+Black",
    "source": "@fontsource/archivo-black@5.3.0, latin subset",
    "brands": [
      "mazal"
    ],
    "note": "Separate Google Fonts family from Archivo 900."
  },
  {
    "family": "Jost",
    "slug": "jost",
    "role": "GN Commune wordmark and tracked caps eyebrows",
    "weights": [
      300
    ],
    "files": [
      {
        "weight": 300,
        "file": "/fonts/jost/jost-latin-300-normal.woff2",
        "bytes": 9876
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/jost/OFL.txt",
    "licenseBytes": 4497,
    "googleUrl": "https://fonts.google.com/specimen/Jost",
    "source": "@fontsource/jost@5.3.0, latin subset",
    "brands": [
      "commune"
    ],
    "note": ""
  },
  {
    "family": "Inter",
    "slug": "inter",
    "role": "GN Commune body text",
    "weights": [
      400,
      500,
      600
    ],
    "files": [
      {
        "weight": 400,
        "file": "/fonts/inter/inter-latin-400-normal.woff2",
        "bytes": 23664
      },
      {
        "weight": 500,
        "file": "/fonts/inter/inter-latin-500-normal.woff2",
        "bytes": 24272
      },
      {
        "weight": 600,
        "file": "/fonts/inter/inter-latin-600-normal.woff2",
        "bytes": 24452
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/inter/OFL.txt",
    "licenseBytes": 4477,
    "googleUrl": "https://fonts.google.com/specimen/Inter",
    "source": "@fontsource/inter@5.3.0, latin subset",
    "brands": [
      "commune"
    ],
    "note": ""
  },
  {
    "family": "Caveat",
    "slug": "caveat",
    "role": "GN Commune handwriting accent",
    "weights": [
      400,
      600
    ],
    "files": [
      {
        "weight": 400,
        "file": "/fonts/caveat/caveat-latin-400-normal.woff2",
        "bytes": 48836
      },
      {
        "weight": 600,
        "file": "/fonts/caveat/caveat-latin-600-normal.woff2",
        "bytes": 51220
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/caveat/OFL.txt",
    "licenseBytes": 4384,
    "googleUrl": "https://fonts.google.com/specimen/Caveat",
    "source": "@fontsource/caveat@5.3.0, latin subset",
    "brands": [
      "commune"
    ],
    "note": ""
  },
  {
    "family": "IBM Plex Mono",
    "slug": "ibm-plex-mono",
    "role": "GN Commune labels",
    "weights": [
      400
    ],
    "files": [
      {
        "weight": 400,
        "file": "/fonts/ibm-plex-mono/ibm-plex-mono-latin-400-normal.woff2",
        "bytes": 14708
      }
    ],
    "license": "SIL Open Font License 1.1",
    "licenseFile": "/fonts/ibm-plex-mono/OFL.txt",
    "licenseBytes": 5299,
    "googleUrl": "https://fonts.google.com/specimen/IBM+Plex+Mono",
    "source": "@fontsource/ibm-plex-mono@5.3.0, latin subset",
    "brands": [
      "commune"
    ],
    "note": ""
  }
];

export function getFontFamily(slug: string): FontManifestEntry | undefined {
  return FONTS_MANIFEST.find((f) => f.slug === slug);
}

export function fontsForBrand(brand: BrandId): readonly FontManifestEntry[] {
  return FONTS_MANIFEST.filter((f) => f.brands.includes(brand));
}

export const FONTS_TOTAL_BYTES: number = FONTS_MANIFEST.reduce(
  (sum, fam) => sum + fam.files.reduce((s, f) => s + f.bytes, 0) + fam.licenseBytes,
  0,
);
