/**
 * Small WebP previews (max 320 px on the long side) for the asset grid and the
 * per-brand download tables, so the UI never loads the full-size originals just
 * to draw a thumbnail. Generated from public/brand into public/brand/_previews.
 * Download buttons still point at the real file in assets.ts.
 */
export interface AssetPreview {
  readonly src: string;
  readonly width: number;
  readonly height: number;
}

export const PREVIEWS: Readonly<Record<string, AssetPreview>> = {
  "ventures-primary-dark": { src: "/brand/_previews/ventures-primary-dark.webp", width: 320, height: 320 },
  "ventures-primary-transparent": { src: "/brand/_previews/ventures-primary-transparent.webp", width: 320, height: 320 },
  "ventures-on-light": { src: "/brand/_previews/ventures-on-light.webp", width: 320, height: 242 },
  "ventures-on-light-svg": { src: "/brand/_previews/ventures-on-light-svg.webp", width: 320, height: 242 },
  "ventures-mono-white": { src: "/brand/_previews/ventures-mono-white.webp", width: 320, height: 242 },
  "ventures-mono-white-svg": { src: "/brand/_previews/ventures-mono-white-svg.webp", width: 320, height: 242 },
  "ventures-mono-ink": { src: "/brand/_previews/ventures-mono-ink.webp", width: 320, height: 242 },
  "ventures-mono-ink-svg": { src: "/brand/_previews/ventures-mono-ink-svg.webp", width: 320, height: 242 },
  "ventures-horizontal": { src: "/brand/_previews/ventures-horizontal.webp", width: 320, height: 242 },
  "ventures-horizontal-svg": { src: "/brand/_previews/ventures-horizontal-svg.webp", width: 320, height: 242 },
  "ventures-horizontal-webp": { src: "/brand/_previews/ventures-horizontal-webp.webp", width: 320, height: 242 },
  "ventures-square": { src: "/brand/_previews/ventures-square.webp", width: 320, height: 320 },
  "ventures-app-icon-1024": { src: "/brand/_previews/ventures-app-icon-1024.webp", width: 320, height: 320 },
  "ventures-apple-touch-180": { src: "/brand/_previews/ventures-apple-touch-180.webp", width: 180, height: 180 },
  "ventures-manifest-192": { src: "/brand/_previews/ventures-manifest-192.webp", width: 192, height: 192 },
  "ventures-manifest-512": { src: "/brand/_previews/ventures-manifest-512.webp", width: 320, height: 320 },
  "ventures-avatar-1024": { src: "/brand/_previews/ventures-avatar-1024.webp", width: 320, height: 320 },
  "ventures-og": { src: "/brand/_previews/ventures-og.webp", width: 320, height: 168 },
  "ventures-og-webp": { src: "/brand/_previews/ventures-og-webp.webp", width: 320, height: 168 },
  "ventures-watermark": { src: "/brand/_previews/ventures-watermark.webp", width: 320, height: 242 },
  "media-primary-dark": { src: "/brand/_previews/media-primary-dark.webp", width: 320, height: 320 },
  "media-primary-transparent": { src: "/brand/_previews/media-primary-transparent.webp", width: 320, height: 320 },
  "media-on-light": { src: "/brand/_previews/media-on-light.webp", width: 320, height: 242 },
  "media-on-light-svg": { src: "/brand/_previews/media-on-light-svg.webp", width: 320, height: 242 },
  "media-mono-white": { src: "/brand/_previews/media-mono-white.webp", width: 320, height: 242 },
  "media-mono-white-svg": { src: "/brand/_previews/media-mono-white-svg.webp", width: 320, height: 242 },
  "media-mono-ink": { src: "/brand/_previews/media-mono-ink.webp", width: 320, height: 242 },
  "media-mono-ink-svg": { src: "/brand/_previews/media-mono-ink-svg.webp", width: 320, height: 242 },
  "media-horizontal": { src: "/brand/_previews/media-horizontal.webp", width: 320, height: 242 },
  "media-horizontal-svg": { src: "/brand/_previews/media-horizontal-svg.webp", width: 320, height: 242 },
  "media-horizontal-webp": { src: "/brand/_previews/media-horizontal-webp.webp", width: 320, height: 242 },
  "media-square": { src: "/brand/_previews/media-square.webp", width: 320, height: 320 },
  "media-app-icon-1024": { src: "/brand/_previews/media-app-icon-1024.webp", width: 320, height: 320 },
  "media-site-icon": { src: "/brand/_previews/media-site-icon.webp", width: 320, height: 320 },
  "media-apple-touch-180": { src: "/brand/_previews/media-apple-touch-180.webp", width: 180, height: 180 },
  "media-site-apple-icon": { src: "/brand/_previews/media-site-apple-icon.webp", width: 180, height: 180 },
  "media-manifest-192": { src: "/brand/_previews/media-manifest-192.webp", width: 192, height: 192 },
  "media-manifest-512": { src: "/brand/_previews/media-manifest-512.webp", width: 320, height: 320 },
  "media-avatar-1024": { src: "/brand/_previews/media-avatar-1024.webp", width: 320, height: 320 },
  "media-og": { src: "/brand/_previews/media-og.webp", width: 320, height: 168 },
  "media-og-webp": { src: "/brand/_previews/media-og-webp.webp", width: 320, height: 168 },
  "media-site-og": { src: "/brand/_previews/media-site-og.webp", width: 320, height: 168 },
  "media-watermark": { src: "/brand/_previews/media-watermark.webp", width: 320, height: 242 },
  "media-mascot-otter": { src: "/brand/_previews/media-mascot-otter.webp", width: 320, height: 320 },
  "academy-primary-dark": { src: "/brand/_previews/academy-primary-dark.webp", width: 320, height: 320 },
  "academy-primary-transparent": { src: "/brand/_previews/academy-primary-transparent.webp", width: 320, height: 320 },
  "academy-on-light": { src: "/brand/_previews/academy-on-light.webp", width: 320, height: 243 },
  "academy-on-light-svg": { src: "/brand/_previews/academy-on-light-svg.webp", width: 320, height: 243 },
  "academy-mono-white": { src: "/brand/_previews/academy-mono-white.webp", width: 320, height: 243 },
  "academy-mono-white-svg": { src: "/brand/_previews/academy-mono-white-svg.webp", width: 320, height: 243 },
  "academy-mono-ink": { src: "/brand/_previews/academy-mono-ink.webp", width: 320, height: 243 },
  "academy-mono-ink-svg": { src: "/brand/_previews/academy-mono-ink-svg.webp", width: 320, height: 243 },
  "academy-horizontal": { src: "/brand/_previews/academy-horizontal.webp", width: 320, height: 243 },
  "academy-horizontal-svg": { src: "/brand/_previews/academy-horizontal-svg.webp", width: 320, height: 243 },
  "academy-horizontal-webp": { src: "/brand/_previews/academy-horizontal-webp.webp", width: 320, height: 243 },
  "academy-square": { src: "/brand/_previews/academy-square.webp", width: 320, height: 320 },
  "academy-app-icon-1024": { src: "/brand/_previews/academy-app-icon-1024.webp", width: 320, height: 320 },
  "academy-site-icon": { src: "/brand/_previews/academy-site-icon.webp", width: 320, height: 320 },
  "academy-apple-touch-180": { src: "/brand/_previews/academy-apple-touch-180.webp", width: 180, height: 180 },
  "academy-site-apple-icon": { src: "/brand/_previews/academy-site-apple-icon.webp", width: 180, height: 180 },
  "academy-manifest-192": { src: "/brand/_previews/academy-manifest-192.webp", width: 192, height: 192 },
  "academy-manifest-512": { src: "/brand/_previews/academy-manifest-512.webp", width: 320, height: 320 },
  "academy-avatar-1024": { src: "/brand/_previews/academy-avatar-1024.webp", width: 320, height: 320 },
  "academy-og": { src: "/brand/_previews/academy-og.webp", width: 320, height: 168 },
  "academy-og-webp": { src: "/brand/_previews/academy-og-webp.webp", width: 320, height: 168 },
  "academy-site-og": { src: "/brand/_previews/academy-site-og.webp", width: 320, height: 168 },
  "academy-watermark": { src: "/brand/_previews/academy-watermark.webp", width: 320, height: 243 },
  "club-primary-dark": { src: "/brand/_previews/club-primary-dark.webp", width: 320, height: 320 },
  "club-primary-transparent": { src: "/brand/_previews/club-primary-transparent.webp", width: 320, height: 320 },
  "club-on-light": { src: "/brand/_previews/club-on-light.webp", width: 320, height: 237 },
  "club-on-light-svg": { src: "/brand/_previews/club-on-light-svg.webp", width: 320, height: 237 },
  "club-mono-white": { src: "/brand/_previews/club-mono-white.webp", width: 320, height: 237 },
  "club-mono-white-svg": { src: "/brand/_previews/club-mono-white-svg.webp", width: 320, height: 237 },
  "club-mono-ink": { src: "/brand/_previews/club-mono-ink.webp", width: 320, height: 237 },
  "club-mono-ink-svg": { src: "/brand/_previews/club-mono-ink-svg.webp", width: 320, height: 237 },
  "club-horizontal": { src: "/brand/_previews/club-horizontal.webp", width: 320, height: 237 },
  "club-horizontal-svg": { src: "/brand/_previews/club-horizontal-svg.webp", width: 320, height: 237 },
  "club-horizontal-webp": { src: "/brand/_previews/club-horizontal-webp.webp", width: 320, height: 237 },
  "club-square": { src: "/brand/_previews/club-square.webp", width: 320, height: 320 },
  "club-app-icon-1024": { src: "/brand/_previews/club-app-icon-1024.webp", width: 320, height: 320 },
  "club-site-icon": { src: "/brand/_previews/club-site-icon.webp", width: 320, height: 320 },
  "club-apple-touch-180": { src: "/brand/_previews/club-apple-touch-180.webp", width: 180, height: 180 },
  "club-site-apple-icon": { src: "/brand/_previews/club-site-apple-icon.webp", width: 180, height: 180 },
  "club-manifest-192": { src: "/brand/_previews/club-manifest-192.webp", width: 192, height: 192 },
  "club-manifest-512": { src: "/brand/_previews/club-manifest-512.webp", width: 320, height: 320 },
  "club-avatar-1024": { src: "/brand/_previews/club-avatar-1024.webp", width: 320, height: 320 },
  "club-og": { src: "/brand/_previews/club-og.webp", width: 320, height: 168 },
  "club-og-webp": { src: "/brand/_previews/club-og-webp.webp", width: 320, height: 168 },
  "club-site-og": { src: "/brand/_previews/club-site-og.webp", width: 320, height: 168 },
  "club-watermark": { src: "/brand/_previews/club-watermark.webp", width: 320, height: 237 },
  "club-mascot-cursor": { src: "/brand/_previews/club-mascot-cursor.webp", width: 44, height: 44 },
  "club-mascot-cursor-2x": { src: "/brand/_previews/club-mascot-cursor-2x.webp", width: 88, height: 88 },
  "labs-primary-dark": { src: "/brand/_previews/labs-primary-dark.webp", width: 320, height: 320 },
  "labs-primary-transparent": { src: "/brand/_previews/labs-primary-transparent.webp", width: 320, height: 320 },
  "labs-on-light": { src: "/brand/_previews/labs-on-light.webp", width: 320, height: 242 },
  "labs-on-light-svg": { src: "/brand/_previews/labs-on-light-svg.webp", width: 320, height: 242 },
  "labs-mono-white": { src: "/brand/_previews/labs-mono-white.webp", width: 320, height: 242 },
  "labs-mono-white-svg": { src: "/brand/_previews/labs-mono-white-svg.webp", width: 320, height: 242 },
  "labs-mono-ink": { src: "/brand/_previews/labs-mono-ink.webp", width: 320, height: 242 },
  "labs-mono-ink-svg": { src: "/brand/_previews/labs-mono-ink-svg.webp", width: 320, height: 242 },
  "labs-horizontal": { src: "/brand/_previews/labs-horizontal.webp", width: 320, height: 242 },
  "labs-horizontal-svg": { src: "/brand/_previews/labs-horizontal-svg.webp", width: 320, height: 242 },
  "labs-horizontal-webp": { src: "/brand/_previews/labs-horizontal-webp.webp", width: 320, height: 242 },
  "labs-square": { src: "/brand/_previews/labs-square.webp", width: 320, height: 320 },
  "labs-app-icon-1024": { src: "/brand/_previews/labs-app-icon-1024.webp", width: 320, height: 320 },
  "labs-site-icon": { src: "/brand/_previews/labs-site-icon.webp", width: 320, height: 320 },
  "labs-apple-touch-180": { src: "/brand/_previews/labs-apple-touch-180.webp", width: 180, height: 180 },
  "labs-site-apple-icon": { src: "/brand/_previews/labs-site-apple-icon.webp", width: 180, height: 180 },
  "labs-manifest-192": { src: "/brand/_previews/labs-manifest-192.webp", width: 192, height: 192 },
  "labs-manifest-512": { src: "/brand/_previews/labs-manifest-512.webp", width: 320, height: 320 },
  "labs-avatar-1024": { src: "/brand/_previews/labs-avatar-1024.webp", width: 320, height: 320 },
  "labs-og": { src: "/brand/_previews/labs-og.webp", width: 320, height: 168 },
  "labs-og-webp": { src: "/brand/_previews/labs-og-webp.webp", width: 320, height: 168 },
  "labs-site-og": { src: "/brand/_previews/labs-site-og.webp", width: 320, height: 168 },
  "labs-watermark": { src: "/brand/_previews/labs-watermark.webp", width: 320, height: 242 },
  "mazal-primary-dark": { src: "/brand/_previews/mazal-primary-dark.webp", width: 320, height: 320 },
  "mazal-on-light": { src: "/brand/_previews/mazal-on-light.webp", width: 320, height: 295 },
  "mazal-mark-white-svg": { src: "/brand/_previews/mazal-mark-white-svg.webp", width: 320, height: 295 },
  "mazal-mono-white": { src: "/brand/_previews/mazal-mono-white.webp", width: 320, height: 295 },
  "mazal-mono-ink": { src: "/brand/_previews/mazal-mono-ink.webp", width: 320, height: 295 },
  "mazal-mono-ink-svg": { src: "/brand/_previews/mazal-mono-ink-svg.webp", width: 320, height: 295 },
  "mazal-square": { src: "/brand/_previews/mazal-square.webp", width: 320, height: 320 },
  "mazal-mark": { src: "/brand/_previews/mazal-mark.webp", width: 320, height: 295 },
  "mazal-mark-lime-svg": { src: "/brand/_previews/mazal-mark-lime-svg.webp", width: 320, height: 295 },
  "mazal-app-icon-1024": { src: "/brand/_previews/mazal-app-icon-1024.webp", width: 320, height: 320 },
  "mazal-site-icon": { src: "/brand/_previews/mazal-site-icon.webp", width: 256, height: 256 },
  "mazal-apple-touch-180": { src: "/brand/_previews/mazal-apple-touch-180.webp", width: 180, height: 180 },
  "mazal-manifest-192": { src: "/brand/_previews/mazal-manifest-192.webp", width: 192, height: 192 },
  "mazal-manifest-512": { src: "/brand/_previews/mazal-manifest-512.webp", width: 320, height: 320 },
  "mazal-avatar-1024": { src: "/brand/_previews/mazal-avatar-1024.webp", width: 320, height: 320 },
  "mazal-og": { src: "/brand/_previews/mazal-og.webp", width: 320, height: 168 },
  "mazal-og-webp": { src: "/brand/_previews/mazal-og-webp.webp", width: 320, height: 168 },
  "mazal-site-og": { src: "/brand/_previews/mazal-site-og.webp", width: 320, height: 168 },
  "mazal-watermark": { src: "/brand/_previews/mazal-watermark.webp", width: 320, height: 295 },
  "mazal-cursor": { src: "/brand/_previews/mazal-cursor.webp", width: 320, height: 320 },
  "commune-logo-sipper": { src: "/brand/_previews/commune-logo-sipper.webp", width: 320, height: 315 },
  "commune-primary-dark": { src: "/brand/_previews/commune-primary-dark.webp", width: 320, height: 320 },
  "commune-primary-light": { src: "/brand/_previews/commune-primary-light.webp", width: 320, height: 313 },
  "commune-on-light": { src: "/brand/_previews/commune-on-light.webp", width: 320, height: 313 },
  "commune-mono-white": { src: "/brand/_previews/commune-mono-white.webp", width: 320, height: 313 },
  "commune-mono-white-svg": { src: "/brand/_previews/commune-mono-white-svg.webp", width: 320, height: 313 },
  "commune-mono-ink": { src: "/brand/_previews/commune-mono-ink.webp", width: 320, height: 313 },
  "commune-mono-ink-svg": { src: "/brand/_previews/commune-mono-ink-svg.webp", width: 320, height: 313 },
  "commune-square": { src: "/brand/_previews/commune-square.webp", width: 320, height: 320 },
  "commune-app-icon-1024": { src: "/brand/_previews/commune-app-icon-1024.webp", width: 320, height: 320 },
  "commune-site-icon": { src: "/brand/_previews/commune-site-icon.webp", width: 320, height: 320 },
  "commune-apple-touch-180": { src: "/brand/_previews/commune-apple-touch-180.webp", width: 180, height: 180 },
  "commune-site-apple-icon": { src: "/brand/_previews/commune-site-apple-icon.webp", width: 180, height: 180 },
  "commune-manifest-192": { src: "/brand/_previews/commune-manifest-192.webp", width: 192, height: 192 },
  "commune-manifest-512": { src: "/brand/_previews/commune-manifest-512.webp", width: 320, height: 320 },
  "commune-avatar-1024": { src: "/brand/_previews/commune-avatar-1024.webp", width: 320, height: 320 },
  "commune-og": { src: "/brand/_previews/commune-og.webp", width: 320, height: 168 },
  "commune-og-webp": { src: "/brand/_previews/commune-og-webp.webp", width: 320, height: 168 },
  "commune-site-og": { src: "/brand/_previews/commune-site-og.webp", width: 320, height: 168 },
  "commune-watermark": { src: "/brand/_previews/commune-watermark.webp", width: 320, height: 313 },
};

export function previewFor(id: string): AssetPreview | undefined {
  return PREVIEWS[id];
}
